- id: deck_light_on
  alias: Lights - Turn on deck_light at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data: {}
    entity_id: light.deck_light
    service: light.turn_on
- id: deck_light_off
  alias: Lights - Turn off deck_light at sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - entity_id: light.deck_light
    service: light.turn_off
- id: front_doorbell
  alias: Lights - Front Door On
  description: Turn on the front light for 2 mins
  trigger:
  - entity_id: binary_sensor.aarlo_motion_front_door
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  action:
  - data: {}
    entity_id: light.front_door
    service: light.turn_on
- id: '1578890862054'
  alias: Lights - Lounge Lights when dark
  description: Turn on the lights if we're home and it's getting dark
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - alias: ''
    data: {}
    entity_id: light.lounge
    service: light.turn_on
- id: '1578901183427'
  alias: Lights - Office Light On If PC Boots
  description: Turn the office light on if the room is dark and the pc is on
  trigger:
  - entity_id: binary_sensor.jimmy_pc
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.office_dark
    state: 'True'
  action:
  - entity_id: light.office
    service: light.turn_on
- id: '1578901442967'
  alias: Lights - Office Light On If Dark
  description: If the PC is already on and it gets dark, turn the light on
  trigger:
  - entity_id: sensor.office_dark
    from: 'False'
    platform: state
    to: 'True'
  condition:
  - condition: state
    entity_id: binary_sensor.jimmy_pc
    state: 'on'
  action:
  - entity_id: light.office
    service: light.turn_on
- id: '1578957557074'
  alias: Lights - Office Motion Sensor On
  description: Turn on the office light if there's motion
  trigger:
  - entity_id: binary_sensor.office_sensor_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.office_dark
    state: 'True'
  action:
  - entity_id: light.office
    service: light.turn_on
- id: '1578957732416'
  alias: Lights - Office Light Off Without Motion
  description: Turn off the lights if no motion for 10 mins and the PC is off
  trigger:
  - entity_id: binary_sensor.office_sensor_motion
    for: 00:10
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.office
    service: light.turn_off
- id: '1579414572379'
  alias: HA - Restart daily
  description: Some add-ons suck and only work after a restart
  trigger:
  - at: 04:00
    platform: time
  condition: []
  action:
  - service: homeassistant.restart
- id: '1579558371441'
  alias: Notification - Take the rubbish out
  description: ''
  trigger:
  - event: sunset
    offset: -00:20:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: state
    entity_id: sensor.rubbish_night
    state: Today
  action:
  - data:
      entity_id: media_player.kitchen_display
      message: Its rubbish night. Time to take out the bins
    service: tts.google_translate_say
- id: '1590219322121'
  alias: Lights - Front Door Off
  description: Turn off after 1 min
  trigger:
  - entity_id: binary_sensor.aarlo_motion_front_door
    for: 00:01
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: light.front_door
    service: light.turn_off
