# Know whether my PC is powered on or not
- platform: ping
  host: 192.168.1.25
  name: Jimmy-PC
  count: 1
  scan_interval: 5

# Arlo sensors
- platform: aarlo
  monitored_conditions:
    - motion
    - sound
    - ding

# Hue Sensors - Enables the light controllers and other thingies
- platform: huesensor