- platform: flux_led
  devices:
    192.168.1.62:
      name: deck_light
      mode: "rgbw"
      custom_effect:
        speed_pct: 100
        transition: 'gradual'
        colors:
          - [255,0,0]
          - [255,255,0]
          - [0,255,0]
          - [0,255,255]
          - [0,0,255]
          - [255,0,255]
